package com.example.oceanedu;

/**
 * Animal Class for creating new animal objects to use in the application
 */
public class Animal {
    private String name;
    private String funFact;
    private String key;

    /**
     * Animal Constructor
     * @param key, takes in the key generated by the firebase db
     * @param name, takes in the name of the animal
     * @param funFact, takes in the fun fact associated with the animal
     */
    public Animal(String key, String name, String funFact) {
        this.key = key;
        this.name = name;
        this.funFact = funFact;
    }

    /**
     * Method to get the key of a specific animal
     * @return, returns the key from the firebase db instance
     */
    public String getKey(){
        return key;
    }

    /**
     * Sets the key to the value generated by the db
     * @param key, takes in the key value to set to the variable
     */
    public void setKey(String key) {

        this.key = key;
    }

    /**
     * Method to get the name of a specific animal
     * @return, returns the name of the animal
     */
    public String getName() {

        return name;
    }

    /**
     * Sets the name of the animal
     * @param name, used to store the name of the animal that is set
     */
    public void setName(String name) {

        this.name = name;
    }

    /**
     * Method to get the fun fact associated with a specific animal
     * @return, returns the fun fact for the animal
     */
    public String getFunFact() {

        return funFact;
    }

    /**
     * Sets the fun fact for the animal
     * @param funFact, stores the entered fun fact for the animal
     */
    public void setFunFact(String funFact) {

        this.funFact = funFact;
    }
}
